# Site settings
title: Kingqh Nest
SEOTitle: 邱恒的小窝 | Kingqh Nest
header-img: img/home-bg.jpg
email: 942972210@qq.com 
description: ""
keyword: ""
url: "http://kingqh.cn"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     kingqh
zhihu_username:     kingqh
github_username:    kingqh
#twitter_username:  kingqh
facebook_username:  kingqh



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
#gems: [jekyll-paginate]
plugins:
  - jekyll-paginate



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: kingqh
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share:  false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: kingqh.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "编写 Java 开发包都是一群神人，拿 Java 源码来分析问题，我们无疑站在了巨人的肩膀上。所谓站得高，尿的远也。当然，所谓偷拍都是避免不了的。"
sidebar-avatar: /img/avatar-qh.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

host: 0.0.0.0

# Friends
friends: [
    {
        title: "Kingqh Blog",
        href: "http://kingqh.cn"
    },{
        title: "张戈网站",
        href: "https://zhang.ge/"
    },{
        title: "纯洁的微笑",
        href: "http://www.ityouknow.com"
    }
]
